dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r dev-requirements.txt
script:
  pytest --pep8 -v --cov mkdocssafetext
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then codecov; fi
