dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install:
  - pip install -r dev-requirements.txt
script:
  pytest --pycodestyle -v --cov mkdocssafetext
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.8" ]]; then codecov; fi
